package com.heineken.greendaoapp.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        ConfiguracionDao.createTable(db, ifNotExists);
        LecturasDao.createTable(db, ifNotExists);
        LotesDao.createTable(db, ifNotExists);
        ProductosDao.createTable(db, ifNotExists);
        RutasDao.createTable(db, ifNotExists);
        SalidasDao.createTable(db, ifNotExists);
        SeccionesDao.createTable(db, ifNotExists);
        UMDao.createTable(db, ifNotExists);
        FamiliaDao.createTable(db, ifNotExists);
        PropiedadesDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        ConfiguracionDao.dropTable(db, ifExists);
        LecturasDao.dropTable(db, ifExists);
        LotesDao.dropTable(db, ifExists);
        ProductosDao.dropTable(db, ifExists);
        RutasDao.dropTable(db, ifExists);
        SalidasDao.dropTable(db, ifExists);
        SeccionesDao.dropTable(db, ifExists);
        UMDao.dropTable(db, ifExists);
        FamiliaDao.dropTable(db, ifExists);
        PropiedadesDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(ConfiguracionDao.class);
        registerDaoClass(LecturasDao.class);
        registerDaoClass(LotesDao.class);
        registerDaoClass(ProductosDao.class);
        registerDaoClass(RutasDao.class);
        registerDaoClass(SalidasDao.class);
        registerDaoClass(SeccionesDao.class);
        registerDaoClass(UMDao.class);
        registerDaoClass(FamiliaDao.class);
        registerDaoClass(PropiedadesDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
