package com.heineken.greendaoapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "LECTURAS".
 */
@Entity
public class Lecturas {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String id_lectura;
    private String sku;
    private String cb;
    private String descripcion;
    private String id_um;
    private String um;
    private String cantidad;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Lecturas() {
    }

    public Lecturas(Long id) {
        this.id = id;
    }

    @Generated
    public Lecturas(Long id, String id_lectura, String sku, String cb, String descripcion, String id_um, String um, String cantidad) {
        this.id = id;
        this.id_lectura = id_lectura;
        this.sku = sku;
        this.cb = cb;
        this.descripcion = descripcion;
        this.id_um = id_um;
        this.um = um;
        this.cantidad = cantidad;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getId_lectura() {
        return id_lectura;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId_lectura(@NotNull String id_lectura) {
        this.id_lectura = id_lectura;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getCb() {
        return cb;
    }

    public void setCb(String cb) {
        this.cb = cb;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getId_um() {
        return id_um;
    }

    public void setId_um(String id_um) {
        this.id_um = id_um;
    }

    public String getUm() {
        return um;
    }

    public void setUm(String um) {
        this.um = um;
    }

    public String getCantidad() {
        return cantidad;
    }

    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
