package com.heineken.greendaoapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "LOTES".
 */
@Entity
public class Lotes {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String _id_;
    private String lote;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Lotes() {
    }

    public Lotes(Long id) {
        this.id = id;
    }

    @Generated
    public Lotes(Long id, String _id_, String lote) {
        this.id = id;
        this._id_ = _id_;
        this.lote = lote;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String get_id_() {
        return _id_;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void set_id_(@NotNull String _id_) {
        this._id_ = _id_;
    }

    public String getLote() {
        return lote;
    }

    public void setLote(String lote) {
        this.lote = lote;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
