package com.heineken.greendaoapp.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRODUCTOS".
*/
public class ProductosDao extends AbstractDao<Productos, Long> {

    public static final String TABLENAME = "PRODUCTOS";

    /**
     * Properties of entity Productos.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sku = new Property(1, String.class, "sku", false, "SKU");
        public final static Property Cb = new Property(2, String.class, "cb", false, "CB");
        public final static Property Ml = new Property(3, String.class, "ml", false, "ML");
        public final static Property Descripcion = new Property(4, String.class, "descripcion", false, "DESCRIPCION");
    }


    public ProductosDao(DaoConfig config) {
        super(config);
    }
    
    public ProductosDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRODUCTOS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SKU\" TEXT NOT NULL ," + // 1: sku
                "\"CB\" TEXT," + // 2: cb
                "\"ML\" TEXT," + // 3: ml
                "\"DESCRIPCION\" TEXT);"); // 4: descripcion
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRODUCTOS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Productos entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSku());
 
        String cb = entity.getCb();
        if (cb != null) {
            stmt.bindString(3, cb);
        }
 
        String ml = entity.getMl();
        if (ml != null) {
            stmt.bindString(4, ml);
        }
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(5, descripcion);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Productos entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSku());
 
        String cb = entity.getCb();
        if (cb != null) {
            stmt.bindString(3, cb);
        }
 
        String ml = entity.getMl();
        if (ml != null) {
            stmt.bindString(4, ml);
        }
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(5, descripcion);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Productos readEntity(Cursor cursor, int offset) {
        Productos entity = new Productos( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // sku
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cb
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ml
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // descripcion
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Productos entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSku(cursor.getString(offset + 1));
        entity.setCb(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDescripcion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Productos entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Productos entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Productos entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
