package com.heineken.greendaoapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PRODUCTOS".
 */
@Entity
public class Productos {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String sku;
    private String cb;
    private String ml;
    private String descripcion;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Productos() {
    }

    public Productos(Long id) {
        this.id = id;
    }

    @Generated
    public Productos(Long id, String sku, String cb, String ml, String descripcion) {
        this.id = id;
        this.sku = sku;
        this.cb = cb;
        this.ml = ml;
        this.descripcion = descripcion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getSku() {
        return sku;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSku(@NotNull String sku) {
        this.sku = sku;
    }

    public String getCb() {
        return cb;
    }

    public void setCb(String cb) {
        this.cb = cb;
    }

    public String getMl() {
        return ml;
    }

    public void setMl(String ml) {
        this.ml = ml;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
