package com.heineken.greendaoapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PROPIEDADES".
 */
@Entity
public class Propiedades {

    @Id(autoincrement = true)
    private Long id;
    private int id_url;
    private String url_server;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Propiedades() {
    }

    public Propiedades(Long id) {
        this.id = id;
    }

    @Generated
    public Propiedades(Long id, int id_url, String url_server) {
        this.id = id;
        this.id_url = id_url;
        this.url_server = url_server;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getId_url() {
        return id_url;
    }

    public void setId_url(int id_url) {
        this.id_url = id_url;
    }

    public String getUrl_server() {
        return url_server;
    }

    public void setUrl_server(String url_server) {
        this.url_server = url_server;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
