package com.heineken.greendaoapp.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROPIEDADES".
*/
public class PropiedadesDao extends AbstractDao<Propiedades, Long> {

    public static final String TABLENAME = "PROPIEDADES";

    /**
     * Properties of entity Propiedades.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Id_url = new Property(1, int.class, "id_url", false, "ID_URL");
        public final static Property Url_server = new Property(2, String.class, "url_server", false, "URL_SERVER");
    }


    public PropiedadesDao(DaoConfig config) {
        super(config);
    }
    
    public PropiedadesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROPIEDADES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ID_URL\" INTEGER NOT NULL ," + // 1: id_url
                "\"URL_SERVER\" TEXT);"); // 2: url_server
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROPIEDADES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Propiedades entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getId_url());
 
        String url_server = entity.getUrl_server();
        if (url_server != null) {
            stmt.bindString(3, url_server);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Propiedades entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getId_url());
 
        String url_server = entity.getUrl_server();
        if (url_server != null) {
            stmt.bindString(3, url_server);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Propiedades readEntity(Cursor cursor, int offset) {
        Propiedades entity = new Propiedades( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // id_url
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // url_server
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Propiedades entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId_url(cursor.getInt(offset + 1));
        entity.setUrl_server(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Propiedades entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Propiedades entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Propiedades entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
