package com.heineken.greendaoapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "SECCIONES".
 */
@Entity
public class Secciones {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String id_seccion;
    private String seccion;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Secciones() {
    }

    public Secciones(Long id) {
        this.id = id;
    }

    @Generated
    public Secciones(Long id, String id_seccion, String seccion) {
        this.id = id;
        this.id_seccion = id_seccion;
        this.seccion = seccion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getId_seccion() {
        return id_seccion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId_seccion(@NotNull String id_seccion) {
        this.id_seccion = id_seccion;
    }

    public String getSeccion() {
        return seccion;
    }

    public void setSeccion(String seccion) {
        this.seccion = seccion;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
