package com.heineken.greendaoapp.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SECCIONES".
*/
public class SeccionesDao extends AbstractDao<Secciones, Long> {

    public static final String TABLENAME = "SECCIONES";

    /**
     * Properties of entity Secciones.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Id_seccion = new Property(1, String.class, "id_seccion", false, "ID_SECCION");
        public final static Property Seccion = new Property(2, String.class, "seccion", false, "SECCION");
    }


    public SeccionesDao(DaoConfig config) {
        super(config);
    }
    
    public SeccionesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SECCIONES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ID_SECCION\" TEXT NOT NULL ," + // 1: id_seccion
                "\"SECCION\" TEXT);"); // 2: seccion
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SECCIONES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Secciones entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getId_seccion());
 
        String seccion = entity.getSeccion();
        if (seccion != null) {
            stmt.bindString(3, seccion);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Secciones entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getId_seccion());
 
        String seccion = entity.getSeccion();
        if (seccion != null) {
            stmt.bindString(3, seccion);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Secciones readEntity(Cursor cursor, int offset) {
        Secciones entity = new Secciones( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // id_seccion
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // seccion
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Secciones entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId_seccion(cursor.getString(offset + 1));
        entity.setSeccion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Secciones entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Secciones entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Secciones entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
