package com.heineken.greendaoapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "UM".
 */
@Entity
public class UM {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String id_um;
    private String um;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public UM() {
    }

    public UM(Long id) {
        this.id = id;
    }

    @Generated
    public UM(Long id, String id_um, String um) {
        this.id = id;
        this.id_um = id_um;
        this.um = um;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getId_um() {
        return id_um;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId_um(@NotNull String id_um) {
        this.id_um = id_um;
    }

    public String getUm() {
        return um;
    }

    public void setUm(String um) {
        this.um = um;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
